### ISSUE TITLE
Command to list local services

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/prisma#1100]
It would be nice to get an overview of the locally deployed services.

**Comment by kbrandwijk** [comment]
I have been experimenting with this, and I think that the following options work well:
- `gc list` -> show the same interactive selection as `gc deploy` for cluster, then display services for that cluster
- `gc list --cluster clusterName` or `gc list -c clusterName` -> display services for cluster, show something like `Cluster clusterName is not running. Run 'graphcool local up --name clusterName' to start the cluster first` when a (local) cluster cannot be reached
- Or: `gc list` -> show all services, grouped by cluster (both local and shared).

Also, this is related to #905, because with multiple local cluster, or the new private clusters, the selection list for clusters should not be hardcoded anymore.

**Comment by kbrandwijk** [comment]
The current `list` command is inconsistent, as it lists local services specific to the project, and all shared cluster services.

**Comment by marktani** [comment]
Closing for now.
