### ISSUE TITLE
Workflow for working with local and shared targets in a team

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1285]
A graphcool service project contains a `.graphcoolrc` file, which contain the targets for a project. When working with multiple developers, it's great to share this file, so everyone is working with the same test/production services.

However, the `.graphcoolrc` also contains local targets. Those are specific to your local machine, and don't work when shared with other developers on the team.

The workaround is to remove the local target manually from `.graphcoolrc`, but then committing it to source control shifts the problem back to the first developer.

I don't have a concrete proposal yet for how to deal with this. Maybe local targets should be in a `.graphcoolrc.local` file or something, that would not be committed to source control?

**Comment by vincenzo** [comment]
Thanks for creating this @kbrandwijk. I am fairly new to GC, so I may have a limited view on things. However, the first thing that comes to mind is this: leave `.graphcoolrc` as it is, and handle the following exception differently: 

```
No service with id 'cj9ttwnlb009h0150kg59sgb0' in account test@test.org. Please check if you are logged in to the right account.
```

Rather than issuing this as an error, you could issue an informative message, and then just create the service that wasn't found with the same `id` found in the `.graphcoolrc` file (if that's possible, of course): 

```
The service with id 'cj9ttwnlb009h0150kg59sgb0' was not found. It will be created now.
```

Thoughts?

**Comment by kbrandwijk** [comment]
The problem about that is that when a new service is created, it also gets a _generated_ id. Your approach would require being able to _specify_ a serviceId when creating, which would require a lot more changes across the stack (both server-side and CLI).

**Comment by vincenzo** [comment]
I suspected as much. Then separating the local target out to a different file that is never checked into a repo seems to be the only alternative. Coming at this with a Unix-like mind, I would suggest that such a file for local targets could easily be living in your `$HOME/.graphcoolrc.local`, where GC could store the references to all the local targets (across many services), rather than ending up with a `.graphcoolrc.local` for each of your `.graphcoolrc`. This way you also avoid the annoying issue of having to explicitly exclude the files from various repos.

**Comment by kbrandwijk** [comment]
These should be specific to the project, because a `dev` target on one project is not the same as a `dev` target for another project, and target names are not unique across all projects.

**Comment by vincenzo** [comment]
But the local target is always called local, isn't it? Maybe I am missing something, but I still think all local targets could be aggregated in a single file, whose content would look a bit like this: 

```
local_targets:
     cj9vulbge1fmp01733782ivar: local/cj9ttwnlb009h0150kg59sgb0
     cj9wmccwo2mqh0148d71od6bu: local/cj9sswnlb009h0150kg59sgb1
... 
... 
```
Where the `id` I am using as keys are the production IDs related to that particular local target.

**Comment by vincenzo** [comment]
What if you don't store the local targets at all? I understand that when one runs `gc deploy -t local` GC looks at the CWD to understand what service to deploy. Assuming a directory for each service, it's safe that in a CWD there is only one service to deploy. Couldn't you then (not sure how, since I don't know the internals) do a check like this: "if there's a local service already deployed for this, then deploy there, else create a new one". Did I make any sense?

**Comment by kbrandwijk** [comment]
No, your local _cluster_ uses the cluster name from `~/.graphcoolrc`. The target name is what you specify when running `gc deploy`. So you can have:
`dev: local/c3......`
`otherdev: secondlocalcluster/c3.....`
`local: othercluster/c3....`
`local: local/c3....`

You're also not limited to one local target per service, so this all has to be explicitly stored.

**Comment by zixia** [comment]
@nikolasburk It looks very complicated and not clear...

I had been studying/using the graphcool framework for weeks and still can not figure the meaning out at the first glance.

```
dev: local/c3......
otherdev: secondlocalcluster/c3.....
local: othercluster/c3....
local: local/c3....
```
