### ISSUE TITLE
Document different components and their relation

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1479]
### Tools

* `prisma`
* `graphql`
* `graphql-config`
* `graphql-config-extension-prisma`
* `graphql-playground`
* `graphql-yoga` (optionally)

These questions should be answered in the documentation:

* What is the role of each tool?
* Do I need all of them?
* How do they tie together?

### Files

* `prisma.yml`
* `.graphqlconfig.yml`

These questions should be answered in the documentation:

* Why do I need two configuration files? What is their relation?

### Notes

* Explain relation to `graphcool-framework`

**Comment by dardub** [comment]
@marktani Currently when you go to graph.cool, it tells you to install graphcool-framework. But when you go to the docs there is no mention of graphcool-framework and only graphcool-cli. I think the home page needs to be updated asap, because I along with many others wasted a lot of time trying to figure out what to be using. 

Also, maybe I'm misunderstanding, but graphcool-framework sounds like a dead end right now, so I wouldn't want any new user installing it.

**Comment by marktani** [comment]
We just released a blog post that ties the mentioned tools together. Go ahead and read it [here](https://blog.graph.cool/tutorial-how-to-build-a-graphql-server-with-graphql-yoga-6da86f346e68).
