### ISSUE TITLE
update React & Apollo Quickstart links, clone instructions

### ISSUE THREAD

**Issue by rdela** [graphcool/prisma#1675]
React & Apollo Quickstart | Prisma Docs 

https://github.com/graphcool/prisma/blob/master/docs/1.0/01-Quickstart/03-Frontend/01-React/01-Apollo.md

> The code for this project can be found on [GitHub](https://github.com/graphcool/frontend-examples/tree/master/react).

link 404s is that supposed to be https://github.com/graphcool-examples/react-graphql/tree/master/quickstart-with-apollo now?

similarly we want to update

```sh
git clone https://github.com/graphcool/frontend-examples.git
cd frontend-examples/react
```
with the correct repo

**Comment by rdela** [comment]
Updates in #1676

> The code for this project can be found on [GitHub](https://github.com/graphcool-examples/react-graphql/tree/master/quickstart-with-apollo).

```
git clone https://github.com/graphcool-examples/react-graphql.git
cd react-graphql/quickstart-with-apollo
```

**Comment by nikolasburk** [comment]
Hi @rdela! Thanks so much for the PR and sorry for the confusion. There are two React quickstart tutorials at the moment: [Fullstack]() & [Frontend Only]().

The fullstack uses the [basic React Fullstack GraphQL boilerplate](https://github.com/graphql-boilerplates/react-fullstack-graphql/tree/master/basic) project.

The one for frontend only is indeed based on the project from the `frontend-examples` repo: https://github.com/graphcool/frontend-examples/tree/master/react So your fixes point to the wrong repo. Nevertheless there were some outdated links in that repo that pointed to `graphcool-examples` rather than the `frontend-examples`. I'll take care of fixing everything and cleaning up links - thanks a lot for catching the broken links here! 👍

**Comment by nikolasburk** [comment]
Thanks a lot pointing out the broken links, all links should be working again now: https://www.prismagraphql.com/docs/quickstart/frontend/react/apollo-shaek6eina 🙌

**Comment by rdela** [comment]
Thanks Nikolas, glad you sorted it now!

**Comment by rdela** [comment]
Still 404ing for me, as does https://github.com/graphcool/frontend-examples/

**Comment by nikolasburk** [comment]
Ah I'm sorry! I just realized the repo was private, it's fixed now 👍

**Comment by rdela** [comment]
Oh good I was worried I was losing it for a sec! Well glad I stayed on it I guess, thanks Nikolas!
