### ISSUE TITLE
resolve the `AuthPayload` type, why?

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1737]
I don't get https://github.com/graphcool/prisma/blob/03c8957c2dd8239c0aca1119ff06a3c7204bc889/examples/auth/src/auth.js#L5

Why AuthPayload have to be resolved? It looks like it works without it.

**Comment by AlexanderChen1989** [comment]
same question

**Comment by nikolasburk** [comment]
Thanks for opening this issue @steida! There was in fact a bug which I just fixed, because the `AuthPayload` resolver was never included in the resolvers that was passed to the `GraphQLServer`.

To answer your question though why it's necessary. The short version is that in this example, it actually doesn't matter because the use case is so simple and there are no relations on the `User` type. However, if you have a relation on the `User` type and would query data from that relation via the `AuthPayload` type, the related data couldn't be resolved.

I created an example that extends the `auth` example [here](https://github.com/nikolasburk/auth-extension). You can run the example per instructions in the README. To observe the behaviour that I described above, you first need to signup with a mutation, e.g.:

```graphql
mutation {
  signup(email: "nikolas@graph.cool", password: "asd") {
    token
    user {
      id
    }
  }
}
```

Then create a `Post` for that `User` (against the Prisma API):

```graphql
mutation {
  createPost(data: {
    title: "ASD"
    author: {
      connect: {
        id: "__POST_ID__"
      }
    }
  }) {
    id
  }
}
```

Now, you can observe the behaviour by sending a `login` mutation in which you're querying `posts` of the `User` via the `AuthPayload` type:

```graphql
mutation {
  login(email: "nikolas@graph.cool", password: "asd") {
    token
    user {
      id
      email
      posts {
        id
        title
      }
    }
  }
}
```

If you add the `AuthPayload` resolver to the `resolvers` object again ([here](https://github.com/nikolasburk/auth-extension/blob/master/src/index.js#L14)), then the `login` mutation successfully returns the `Post`. Otherwise it returns the error message: ` "Cannot return null for non-nullable field User.posts."`

To learn more about _why_ that is be sure to check out this blog post: [GraphQL Server Basics: Demystifying the `info` Argument in GraphQL Resolvers](https://blog.graph.cool/graphql-server-basics-demystifying-the-info-argument-in-graphql-resolvers-6f26249f613a)
