### ISSUE TITLE
Multiple identical subscriptions on CREATE

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1763]
**Current behavior**
Prisma local send duplcate subscriptions.

**Reproduction**
Open more than 2 playground and start same subscription requests and send create request.

For 3 connections receive three notifications in each window. For 5 - 5 notifications in each window. And etc...

![a411b431d4](https://user-images.githubusercontent.com/2550668/35494599-b9d1ca62-04cc-11e8-834a-6ddcac99bc5e.png)

**Expected behavior?**
One notification per one ws-connection.

**Comment by oxy88** [comment]
Same

**Comment by marktani** [comment]
Are you experiencing this when connecting directly to your Prisma endpoint, or when connecting indirectly via another GraphQL Server?

**Comment by Fi1osof** [comment]
@marktani i do not us another GraphQL server. I use prisma local. But this problem i have when connect via appolo-client too. In termanal logs i receive multiple notifications too.

**Comment by flintc** [comment]
@marktani If I understand correctly, I am only seeing this issue when connecting indirectly via graphql-yoga GraphQLServer. Running graphql playground I can test subscriptions on the database and application side. The multiple firings only occur on the app side. Each message is sent to each client multiple times equal to the number of clients that have connected since starting the server. Subscriptions in graphql-yoga that don’t use prisma-bindings work as expected.

**Comment by flintc** [comment]
Perhaps this is due to the fact that graphql-yoga (or any other server) acts as a proxy server when used with prisma. Browser connections would be made with the proxy server, not the prisma endpoint. When the browser is closed, the underlying prisma server is unaware and continues to try and send messages to these ghost clients. This would explain why there is no issue with subscriptions made directly with the prisma endpoint. And also why there is no issue with graphql-yoga subscriptions that don't rely on prisma.

**Comment by Fi1osof** [comment]
@flintc i agree

**Comment by oiojin831** [comment]
I have this problem with react-native. Does anyone know how to solve this problems?

**Comment by oiojin831** [comment]
Isn't this related to this issue?
https://github.com/graphcool/graphql-yoga/issues/101#event-1458329589

**Comment by marktani** [comment]
@oiojin831 did you try upgrading your versions as discussed in the link you mentioned?

**Comment by oiojin831** [comment]
@marktani Yes, this is not a problem for me anymore.
I was mentioning this cause I thought this can be closed 😄

**Comment by marktani** [comment]
Hey @oiojin831, that's what I thought 🙂 Thanks for the confirmation!

@Fi1osof, I'm closing this issue as it seems resolved, please open another one if you're still encountering any problems!

**Comment by ramsaylanier** [comment]
So, I was having this issue as well, where I would create an item and the subscription would update the query multiple times. Its seems this issue has been fixed (meaning that the query is only updated once) but when I'm logging all the queries, I still see "mutation: CREATED" an increasing number of times until I do a browser refresh.

Here's the mutation in playground.
<img width="1186" alt="screen shot 2018-02-16 at 4 59 38 pm" src="https://user-images.githubusercontent.com/2359852/36331194-da39a9ce-133a-11e8-927a-4db0e58f6890.png">

Here's the subscription in playground. It only gets one response.
<img width="1185" alt="screen shot 2018-02-16 at 5 00 51 pm" src="https://user-images.githubusercontent.com/2359852/36331230-fb493ddc-133a-11e8-835e-bd95063997b1.png">

HOWEVER, here is what is logged to the terminal. This is after creating several rules.

![screen shot 2018-02-16 at 5 01 37 pm](https://user-images.githubusercontent.com/2359852/36331254-1441b4cc-133b-11e8-873f-f86280d86e42.png)

So, I'm concerned this is still an issue.

**Comment by pungggi** [comment]
yes still an issue
