### ISSUE TITLE
How make it work with Docker Toolbox? (question)

### ISSUE THREAD

**Issue by MichelDiz** [graphcool/prisma#1844]
I'm using the Docker Toolbox that create a virtual-machine in VirtualBox. Working, but Prisma doesn't see the daemon.

**Comment by akoenig** [comment]
Hey @MichelDiz – As far as I remember, Docker Toolbox comes with a special bash. I guess that you use the Docker Toolbox on Windows, right? I have no Windows box at hand, but could you ensure to execute `prisma local start` within that special environment?

**Comment by LFP6** [comment]
I actually just ran into this myself. Make sure that after you install Docker toolbox, you reboot, and then once you go back in make sure Docker has started. That *should* allow you to run the Prisma commands within cmd. Otherwise, what @akoenig most likely applies - I still have to do some testing with it to verify.

I would suggest that this information (whatever winds up being the complete answer) gets added to the install instructions for those not familiar with Docker.

**Comment by MichelDiz** [comment]
yeah! just start the toolbox terminal and then switch to the project folder path and hence "local prism start".

I'm using Mac OS bytheway. Thank you @akoenig and @LFP6 !

Cheers.

**Comment by akoenig** [comment]
@MichelDiz I highly recommend using [Docker for Mac](https://docs.docker.com/docker-for-mac/), when you are running macOS – a much smoother experience :)
