### ISSUE TITLE
support sequel pro and redis

### ISSUE THREAD

**Issue by bharath917** [graphcool/prisma#1954]
# Feature Request

**What feature are you missing?**
1) add in-memory database like redis
2) view mysql data with sequel pro 
3) out of the box authentication with google and facebook
**How could this feature look like in detail? Tradeoffs?**

**Comment by akoenig** [comment]
Hi @bharath917 - Thanks for your issue :tada: 

> 1. add in-memory database like redis

There are plans for supporting Redis. You should subscribe to https://github.com/graphcool/prisma/issues/1722 in order to stay in the loop.

> 2. view mysql data with sequel pro

That is already possible. The `mysql` instance runs in a Docker container and is mapped to your local port `3307`. You can connect to this instance via Sequel Pro with these credentials:

  Host: `localhost`
  User: `root`
  Password: `graphcool`
  Port: `3307`

> 3. out of the box authentication with google and facebook

Yap, that is true. I'm not sure if an out-of-the-box solution is planned. @marktani Could you shed some light on this? :)

**Comment by marktani** [comment]
Thanks @bharath917 for your questions and thanks @akoenig for the answers 😄

Here is an example that shows Github auth: https://github.com/graphcool/prisma/tree/master/examples/github-auth

It should be fairly straightforward to adapt the Github example to Facebook, for example. Let me know if you have any questions about that!

Can you further describe what an ootb solution for Google or Facebook would look like? :)

**Comment by bharath917** [comment]
@marktani Thanks for replying
just to make the new developers'(includes me, therefore facing issues) life simple, adding in authentication with google and facebook,
the flow would look something similar - developer creates a 'google signup' and 'facebook signup' button in the RN app and links it to the backend, the server takes care of backend validation, storing the info, etc., after the dev provides app id in .env,  like the current email-password setup. 
Also how to use phone number instead of email to login?
a choice to use phone or email to log in would be awesome  :)

**Comment by bharath917** [comment]
hey @akoenig  thanks for the reply
successfully connected sequel pro for db

**Comment by akoenig** [comment]
Awesome! You're very welcome 😄

**Comment by marktani** [comment]
Sounds like a great idea, @bharath917! We could add Google and Facebook examples to our repository. Feel free to also ping me [in Slack](slack.graph.cool) if you feel like contributing them yourself 🙌

Anyway, I'm closing this issue as your questions have been answered.
