### ISSUE TITLE
CLI Auth fails to create cloud session key when running non-interactively 

### ISSUE THREAD

**Issue by jgeschwendt** [graphcool/prisma#1987]
# Bug Report

**Current behavior**

Our current node development environment is contained inside of docker containers. When trying to login to create the cloud session key the operation fails when the cli attempts to open a browser.

```
execute callback with error
Error: Command failed: yarn run prisma:login

Authenticating...
 ▸    Exited with code 3

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
error Command failed with exit code 1.

yarn run v1.3.2
$ cross-env prisma login
Opening https://app.prisma.sh/cli-auth?secret=$2a$08$YIosUtpzoBg686TTZtYHDO in the browser

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:236:11)
    at <anonymous>
```

**Expected behavior?**

The error is handled and the process waits for the cloud session key to be manually generated by a developer  copy and pasting the url from the cli output

**Comment by marktani** [comment]
Hey @jgeschwendt, that sounds like a good idea to improve this workflow.

For now, you can use `prisma login --key <key>`. Here's an example: https://www.prismagraphql.com/docs/reference/cli-command-reference/cloud/prisma-login-shaip5yaej

**Comment by jexh** [comment]
I am still having this problem in prisma 1.15.1, which I believe should have the fix. For background, I was following this tutorial, https://www.howtographql.com/react-apollo/1-getting-started/ which includes a download of https://codeload.github.com/howtographql/react-apollo/tar.gz/starter which uses prisma. When running through this, from a docker container, I encountered the problem described above. I updated the "starter" download to the latest version of Prisma and found that the problem is still present.

(I don't understand how the link above shows me how to get round this: there is no key in ~/.prisma in the container.)
