### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by fonzied** [graphcool/prisma#2032]
# Bug Report

`Message:  Your token is invalid. It might have expired or you might be using a token from a different project.`

This error started right after logging into Prisma Cloud for the first time. I didn't change anything whatsoever, just logged in and looked around for about 45 seconds then closed. Even manually inserting new Authorization tokens in the playground gave the same error. I honestly have no idea if Prisma Cloud had any effect but it really did happen shortly after.

It seems like something completely invalidated my Prisma endpoint. I fixed it by redeploying (with a different endpoint) and transferring my data over, but still quite annoying.

**Comment by marktani** [comment]
From your description it sounds like you might have ended up using an old token, or the token from another service.

As your issue is resolved, I'll close this one.

We're thinking about how to improve the error message for a wrong token. If you have any input on this, please share it here: #2190.

Thanks 🙌
