### ISSUE TITLE
Ability to verify a user or root token

### ISSUE THREAD

**Issue by flagello** [graphcool/prisma#209]
Akin to [Firebase `verifyIdToken()` method](https://firebase.google.com/docs/auth/admin/verify-id-tokens).

**Comment by marktani** [comment]
Do you imagine something else than the `user` query?

```graphql
query {
  user {
    id
  }
}
```

If the token is valid, `user` is non-null and the corresponding `id` will be returned. Otherwise, `user` is `null`.

**Comment by flagello** [comment]
That would not be possible server-side using a permanent auth token, correct?

Scenario: the client sends the token to the server with a secure cookie. How does the server know that the token is authentic?

**Comment by marktani** [comment]
Ahh, I'm sorry I misunderstood. I'll adjust the title to clarify what you mean.

This is related to #80.

**Comment by flagello** [comment]
Actually I meant verifying a _user_ token _server-side_ using a PAT — not verifying the PAT itself. Sorry if I wasn't clear enough.

**Comment by marktani** [comment]
😄 I'm sorry for the confusion! Typically we would offer the mutation and hook it in with our available permission system, so you can control who has access to it. That's what got me confused, sorry :)

**Comment by flagello** [comment]
No worries! :)

**Comment by pbandjs** [comment]
Would love to have this feature. I am attempting to build a fairly large application and as such have a giant schema with mutations generally involving multiple nested connections and complex permission conditions. Reasoning about security using the permissions query pattern has pretty much melted by brain. My alternative approach was to remove all permissions from all types and wrap all the necessary queries and mutations my app needs in Schema Extensions in which i would perform the necessary auth and permissions checks. When i started doing this, however, I quickly realised that there is no way to actually authenticate a user in a Schema Extension using a graphcool token ( if there is a way, i was unable to find it ). Since Schema Extensions bypass the permissions system using PATs, without auth i cant really see how I could use them to perform actions on Types which are not already more or less "open" to everyone, which kinda sucks.

**Comment by marktani** [comment]
> there is no way to actually authenticate a user in a Schema Extension using a graphcool token

That's not correct, but we need to do a better job documenting that 🙂 Here's an example how you can check if a request to a schema extension function had a valid authentication token in the `Authorization` header:

https://github.com/graphcool-examples/graphcool-examples/blob/master/email-password-login-instagram/code/authenticatedEmailUser.js#L27-L37

The `event.context.auth.nodeId` will only be populated if the token is valid (that is, it is correctly signed - that doesn't mean that the node exists).

Furthermore, we'll implement the `verifyToken` function in `graphcool-lib`: https://github.com/graphcool/graphcool-lib/blob/master/src/index.ts#L58

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
