### ISSUE TITLE
Prisma Deploy – generated prisma.graphql file is commented out halfway through

### ISSUE THREAD

**Issue by harrysolovay** [graphcool/prisma#2125]
# Bug Report

**Current behavior**

The generated prism.graphql file gets commented out halfway through:

<img width="628" alt="screen shot 2018-03-20 at 12 26 36 pm" src="https://user-images.githubusercontent.com/4893548/37668313-8ede41a6-2c3a-11e8-8dd5-0b6db7db55a9.png">

**Reproduction**

<img width="533" alt="screen shot 2018-03-20 at 12 27 16 pm" src="https://user-images.githubusercontent.com/4893548/37668330-977972ea-2c3a-11e8-86d2-6bdc7a6baca7.png">

<img width="826" alt="screen shot 2018-03-20 at 12 27 01 pm" src="https://user-images.githubusercontent.com/4893548/37668556-3219bba2-2c3b-11e8-935d-db5a13050933.png">

<img width="1009" alt="screen shot 2018-03-20 at 12 36 48 pm" src="https://user-images.githubusercontent.com/4893548/37668676-6cdcbb7c-2c3b-11e8-9f98-89fe8d9b9e51.png">

<img width="777" alt="screen shot 2018-03-20 at 12 38 16 pm" src="https://user-images.githubusercontent.com/4893548/37668774-a61379c6-2c3b-11e8-972d-6b53d979532b.png">

**Expected behavior?**

I'm trying to run a simple query to get the user with a given facebookID. For now, I forward the given user query to the db, and call it like this:

`let user = await ctx.db.query.user({ where : { facebookId : facebookUser.id } })`

It's giving me this error message: "Variable \"$_where\" got invalid value {\"facebookId\":\"1066677483399188\"}; Field \"facebookId\" is not defined by type UserWhereUniqueInput."

Please help me fix this! I believe this to be a bug related to the auto-generated file... but maybe I've also wrongly implemented it (I'm very new to Prisma). What do I do?

**Comment by harrysolovay** [comment]
Just noticed that I wasn't using UserWhereInput and not UserWhereUniqueInput, which I then changed. I also adjusted my query to the following:

`
  user(parent, args, ctx, info) {
    return ctx.db.query.user({
      where : {
        facebookId
      }
    }, info)
  }

`

I'm still getting an error: "Variable \"$_where\" got invalid value {\"facebookId\":\"1066677483399188\"}; Field \"facebookId\" is not defined by type UserWhereUniqueInput."

**Comment by marktani** [comment]
Hey @harrysolovay, you are encountering two separate problems.

You receive this error message because your `User` type does not specify the `facebookId` to be `@unique`. Please change line 8 in`datamodel.graphql` to

`facebookId!: String @unique`

then `prisma deploy` and let it regenerate the `prisma.ts` file. Your original code should then work as expected.

The cosmetic problem has been brought up before by @johannpinson [here](https://github.com/graphcool/prisma/issues/2047). He concluded that this requires a change in the `graphql-js` library, and added a new issue for this [here](https://github.com/graphql/graphql-js/issues/1285). Please join the discussion there, to raise awareness about this problem 🙂 

Let me know if you need further help with your first issue.

**Comment by harrysolovay** [comment]
Worked like a charm! Thank you!!!
