### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#589]
Currently the subscriptions API is automatically generated from the model types in a project.
This feature request introduces the ability to extend the subscription API with custom events.

**Defining Custom events**

A custom event can be added to the `types.graphql` file like this:

```graphql
type MyEvent @event {
  title: String!
  user: User!
}
```

**Publishing Custom events**

Custom events can be published using [graphcool-lib](https://github.com/graphcool/graphcool-lib). When publishing an event you must include the type name and a json object containing all required data.

In the example above one of the fields is a Graphcool model type. In this case, instead of providing the entire `User` node, the id of an existing `User` must be provided:

```js
graphcool.event('MyEvent', {title: 'this is an event', user: 'id-of-existing-user'})
```

**Subscribing to Custom events**

Custom events can be subscribed to with a normal subscription query from both frontend and backend.

Custom events should implement the normal permission system.

Custom events should support normal filters including relations

**Comment by kbrandwijk** [comment]
This would also require a change to the subscription filter, because this is not a 1-on-1 match with `CREATE`. Also, as this closely resembles the socket.io/realtime.co/others... implementation of 'channels', there might be a more standardized feature hidden in here: Type name is basically the same as channel name, and the type definition is just a strongly typed message payload.

I would suggest the following convenience methods on `graphcool-lib`:
- `graphcool.publish` instead of `graphcool.event`
- `graphcool.subscribe` as a one-liner to set up a subscription

`graphcool.publish('ChannelName', stronglyTypedPayloadJson)`
`graphcool.subscribe('ChannelName').on('data', (data) => { console.log(data) })`

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
