### ISSUE TITLE
Inactive Functions and Permissions are not visible in the graphcool.yml

### ISSUE THREAD

**Issue by do4gr** [graphcool/prisma#705]
We do not print out inactive Functions and PermissionQueries to the graphcool.yml at the moment. This can lead to confusion if the user later on tries to create a Function with the same name or in the case of a RP function tries to create one for the same model, binding and operation and gets an error that the local yml will not give him any clue about.

**Comment by schickling** [comment]
As a workaround we should print but comment-out disabled functions/permissions while "ejecting" them from the legacy state.

**Comment by kbrandwijk** [comment]
Commenting out is a rather awkward way to deal with this. At first sight, it makes sense to add commented-out entries for disabled functions/permissions, but would a new deploy not complete remove them then?
The enabled option was removed from the graphcool.yml because support for it would end, but it seems that for the transition phase the only way to not risk loosing anything is by re-adding support for enabled:true on functions and permissions again.

**Comment by marktani** [comment]
Commenting out and deploying will remove the disabled function/permission from the project. This is no "functional" change, as they were disabled before.

All functions and permission queries are still persisted on the file system. The only thing getting lost is disabled permissions without a permission query.

I think this is a fair trade-off.

**Comment by kbrandwijk** [comment]
I like the enabled/disabled flag on functions, because you can't conditionally comment something, but you can use an environment variable to enable a stub function on dev, while actually connecting to a third party in production. However, this is a different use case, that's unrelated to this.

**Comment by FredyC** [comment]
When a function is disabled in UI and I try to run deploy, I get an error message `Function with name 'DisabledFunction' has invalid payloadName: 'SomePayload'`. It's really confusing, especially since it talks about a function I haven't even modified :)

Reading discussion here, I'll add my two cents. What's the purpose of disabling a function with a new framework? With the legacy approach, I've used it once mostly just to mark the function that is broken. I cannot think of use case where you would disable a function that is actually used somewhere and causing unhandled errors because of that.

If you want to keep this feature, I think it should be just ignored by a new framework. Meaning when you deploy, the function code is updated, but its enabled status is kept. Although then we are getting back to the topic of use case and why would you update code for something that you don't want to use. CLI would probably need to warn about it.

Another option is to have `disabled` flag directly in `graphcool.yml` so instead of commenting out whole function block, you would just add this flag and deploy. Suddenly it's not just some transient state that you can control with web interface only, but it's also part of version control.

**Comment by kbrandwijk** [comment]
@FredyC That's what I meant with 'liking the enabled/disabled flag of functions', in the project file. It used to be in one of the earliest versions of the CLI beta. I already described one use case for it, which is enabling/disabling function versions specific to an environment. Having a logging function enabled only in dev/test for example, or a stub function for an external system that is not available in dev.
I think it shouldn't be a part of the console at all. Actually, I believe in a headless system, and I don't believe that any of the features related to functions should be a part of the console anymore.

**Comment by FredyC** [comment]
Well, your use case still does not make much sense. Imagine that your app would be calling that logging function. Suddenly you disable it and those requests start to fail. Why not disable logging in the code of your app instead of sending useless requests in a production app?

**Comment by FredyC** [comment]
In my opinion list of functions in Console should be used purely for advanced display of logs only. I would not remove it completely. CLI is kinda limited for visual interactions.

**Comment by kbrandwijk** [comment]
@FredyC You are just thinking about resolver functions. Disabling those would break client apps. However, there are also operation hooks, and subscription functions. And even for resolver functions, disabling one, and enabling another, based on environment, also does not break client apps.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
