### ISSUE TITLE
Downloading the project definition with content doesn't always work on Windows

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#769]
**What is the current behavior?**

On Windows, the zip containing the project definition with file content obtained from the project settings in the Console for a project that contains either

* a permission query
* a resolver

does not include the actual function/query files, but references them in the `graphcool.yml` file, when downloading the zip on Windows. Maybe this is triggered by a special function/permission file name as well (spaces?).

**What is the expected behavior?**

The zip should contain those files.

**Comment by kbrandwijk** [comment]
Windows needs the explicit `{createFolders: true}` option when calling `zip.file()` here: https://github.com/graphcool/console/blob/24e637a96b73347aaa1e607c453e8631c0ec3d96/src/views/Settings/General/ProjectInfo.tsx#L349.

Otherwise, JSZip will default to creating a 'virtual folder', which is not supported on Windows

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
